In [ ]:
from google.colab import files

uploaded = files.upload()

Saving adult.csv to adult.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
#Task 1 — Fix Hidden Missing Values
dataset = pd.read_csv("adult.csv")
# dataset.info()
# dataset.isnull().sum()
colList = dataset.columns
for i in colList:
  dataset[i].replace('?', np.nan, inplace=True)
dataset.isnull().sum()

/tmp/ipykernel_1489/385554930.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset[i].replace('?', np.nan, inplace=True)

age                  0
workclass         1836
fnlwgt               0
education            0
education.num        0
marital.status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital.gain         0
capital.loss         0
hours.per.week       0
native.country     583
income               0
dtype: int64

In [ ]:
# Task : 2  Quantify Missingness
null_percentage = (dataset.isnull().mean() * 100).sort_values(ascending=False)
null_percentage.head(1)

occupation    5.660146
dtype: float64

In [ ]:
# Task : 3: Handle Missing Values
for i in colList:
  if i == 'workclass' or 'occupation':
    dataset[i].replace(np.nan, 'Unknown')

for i in colList:
  if dataset[i].isin(['Unknown']).any():
    print("TRUE")

In [27]:
# TASK : 4: Detect Duplicates
exact_duplicates = dataset.duplicated().sum()
print(f"Exact duplicate rows: {exact_duplicates}")

dup_ignoring_income = dataset.duplicated(subset=dataset.columns.drop('income')).sum()
print(f"Duplicates ignoring target (income) are: {dup_ignoring_income}")

Exact duplicate rows: 24
Duplicates ignoring target (income) are: 25

In [35]:
# TASK : 5: Fix Inconsistent Categorical Data
t5_list = ['native.country', 'marital.status', 'education']
print("==== BEFORE STRIPING ====")
for i in t5_list:
  print(dataset[i].unique())
  print()

print('\n')
print("==== AFTER STRIPING =====")
for i in t5_list:

  dataset[i] = dataset[i].str.strip()
  print(dataset[i].unique())
  print()

==== BEFORE STRIPING ====
['United-States' nan 'Mexico' 'Greece' 'Vietnam' 'China' 'Taiwan' 'India'
 'Philippines' 'Trinadad&Tobago' 'Canada' 'South' 'Holand-Netherlands'
 'Puerto-Rico' 'Poland' 'Iran' 'England' 'Germany' 'Italy' 'Japan' 'Hong'
 'Honduras' 'Cuba' 'Ireland' 'Cambodia' 'Peru' 'Nicaragua'
 'Dominican-Republic' 'Haiti' 'El-Salvador' 'Hungary' 'Columbia'
 'Guatemala' 'Jamaica' 'Ecuador' 'France' 'Yugoslavia' 'Scotland'
 'Portugal' 'Laos' 'Thailand' 'Outlying-US(Guam-USVI-etc)']

['Widowed' 'Divorced' 'Separated' 'Never-married' 'Married-civ-spouse'
 'Married-spouse-absent' 'Married-AF-spouse']

['HS-grad' 'Some-college' '7th-8th' '10th' 'Doctorate' 'Prof-school'
 'Bachelors' 'Masters' '11th' 'Assoc-acdm' 'Assoc-voc' '1st-4th' '5th-6th'
 '12th' '9th' 'Preschool']



==== AFTER STRIPING =====
['United-States' nan 'Mexico' 'Greece' 'Vietnam' 'China' 'Taiwan' 'India'
 'Philippines' 'Trinadad&Tobago' 'Canada' 'South' 'Holand-Netherlands'
 'Puerto-Rico' 'Poland' 'Iran' 'England' 'Germany' 'Italy' 'Japan' 'Hong'
 'Honduras' 'Cuba' 'Ireland' 'Cambodia' 'Peru' 'Nicaragua'
 'Dominican-Republic' 'Haiti' 'El-Salvador' 'Hungary' 'Columbia'
 'Guatemala' 'Jamaica' 'Ecuador' 'France' 'Yugoslavia' 'Scotland'
 'Portugal' 'Laos' 'Thailand' 'Outlying-US(Guam-USVI-etc)']

['Widowed' 'Divorced' 'Separated' 'Never-married' 'Married-civ-spouse'
 'Married-spouse-absent' 'Married-AF-spouse']

['HS-grad' 'Some-college' '7th-8th' '10th' 'Doctorate' 'Prof-school'
 'Bachelors' 'Masters' '11th' 'Assoc-acdm' 'Assoc-voc' '1st-4th' '5th-6th'
 '12th' '9th' 'Preschool']

In [41]:
# TASK : 6 : Descriptive Statistics
print("==============================================")
print(dataset.describe())
print(dataset.describe(include='object'))
print("==============================================")

print()
print()
print("==============================================")
print("Age:")
print("Mean:", dataset['age'].mean())
print("Median:", dataset['age'].median())
print("==============================================")

print()
print()
print("==============================================")
print("Hours per week:")
print("Mean:", dataset['hours.per.week'].mean())
print("Median:", dataset['hours.per.week'].median())
print("==============================================")

==============================================
                age        fnlwgt  education.num  capital.gain  capital.loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000

       hours.per.week
count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000
       workclass education      marital.status      occupation relationship  \
count      30725     32561               32561           30718        32561
unique         8        16                   7              14            6
top      Private   HS-grad  Married-civ-spouse  Prof-specialty      Husband
freq       22696     10501               14976            4140        13193

         race    sex native.country income
count   32561  32561          31978  32561
unique      5      2             41      2
top     White   Male  United-States  <=50K
freq    27816  21790          29170  24720
==============================================


==============================================
Age:
Mean: 38.58164675532078
Median: 37.0
==============================================


==============================================
Hours per week:
Mean: 40.437455852092995
Median: 40.0
==============================================

In [54]:
# TASK : 7: Frequency Analysis
print("Most common occupation is: ", dataset['occupation'].value_counts().head(1).index[0])
male = dataset['sex']

print("Percentage of male:", ((dataset['sex'] == 'Male').sum() / len(dataset['sex'])) * 100)
print("Percentage of female: ", ((dataset['sex'] == 'Female').sum() / len(dataset['sex'])) * 100)

print("Percentage of <=50K:", ((dataset['income'] == '<=50K').sum() / len(dataset['income'])) * 100)
print("Percentage of >50K:", ((dataset['income'] == '>50K').sum() / len(dataset['income'])) * 100)


# there is a disparity, alot of people with less than 50k income

Most common occupation is:  Prof-specialty
Percentage of male: 66.92054912318419
Percentage of female:  33.07945087681583
Percentage of <=50K: 75.91904425539757
Percentage of >50K: 24.080955744602438

In [58]:
# Task 8— Cross-Check a Data Quality Assumption
education_check = dataset.groupby('education')['education.num'].unique()
print(education_check.sort_values(ascending=False))

education
Doctorate       [16]
Prof-school     [15]
Masters         [14]
Bachelors       [13]
Assoc-acdm      [12]
Assoc-voc       [11]
Some-college    [10]
HS-grad          [9]
12th             [8]
11th             [7]
10th             [6]
9th              [5]
7th-8th          [4]
5th-6th          [3]
1st-4th          [2]
Preschool        [1]
Name: education.num, dtype: object

In [63]:
#Task 9— SQL-Based Data Extraction
import pandas as pd
import sqlite3

original_df = pd.read_csv("adult.csv")

print("Original shape:", original_df.shape)
conn = sqlite3.connect("adult_income.db")

original_df.to_sql(
    "adult_income",
    conn,
    if_exists="replace",
    index=False
)
query = """
SELECT *
FROM adult_income
WHERE age > 30
"""

sql_df = pd.read_sql_query(query, conn)

print(sql_df.head())

sql_df = pd.read_sql_query("select count(*) from adult_income", conn)
sql_df

Original shape: (32561, 15)
   age workclass  fnlwgt     education  education.num marital.status  \
0   90         ?   77053       HS-grad              9        Widowed
1   82   Private  132870       HS-grad              9        Widowed
2   66         ?  186061  Some-college             10        Widowed
3   54   Private  140359       7th-8th              4       Divorced
4   41   Private  264663  Some-college             10      Separated

          occupation   relationship   race     sex  capital.gain  \
0                  ?  Not-in-family  White  Female             0
1    Exec-managerial  Not-in-family  White  Female             0
2                  ?      Unmarried  Black  Female             0
3  Machine-op-inspct      Unmarried  White  Female             0
4     Prof-specialty      Own-child  White  Female             0

   capital.loss  hours.per.week native.country income
0          4356              40  United-States  <=50K
1          4356              18  United-States  <=50K
2          4356              40  United-States  <=50K
3          3900              40  United-States  <=50K
4          3900              40  United-States  <=50K

   count(*)
0     32561

In [ ]:
# TASK 10 SUMMARY

# Rows = 32561, col = 15. It represents demographic and employment information about individuals, including age, education, occupation, marital status, sex, hours worked per week, and income. The target income variable indicates whether an individual's annual income is <=50K or >50K.

# there weren;t missing values there were just '?' so we replaced those with np.nan

# some values had trailing or leading whitespaces that lead to analysis inconsistency so we removed it

# I didnt drop the nan because dataset is small and dropping will affect the actual analysis

# income is imbalanced, 75% are below <=50k